dist: trusty
sudo: required
language: node_js
node_js:
  - "8.12.0"
cache: npm
before_install:
  - sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - sudo apt-get install bitcoind -y
apt_packages:
  - bitcoind
before_script:
  - npm install
  - npm install -g ganache-cli
  - mkdir -p /home/travis/.bitcoin && cp bitcoin.conf /home/travis/.bitcoin/bitcoin.conf
  - bitcoind -reindex -txindex -regtest -daemon -rpcport=18443 -rpcuser=bitcoin -rpcpassword=local321 -deprecatedrpc=signrawtransaction
script:
  - CI=false ganache-cli -k petersburg &
  - CI=false npm run test
after_script:
  - npx codechecks
  - npm run coverage && cat coverage/lcov.info | coveralls